name       : liburing
version    : 0.7
release    : 1
source     :
    - https://github.com/axboe/liburing/archive/liburing-0.7.tar.gz : 8e2842cfe947f3a443af301bdd6d034455536c38a455c7a700d0c1ad165a7543
license    : MIT
component  : system.utils
summary    : Library for interacting with the io_uring Linux kernel functionality
description: |
    `liburing` provides helpers to setup and teardown io_uring instances, and also a simplified interface for
    applications that don't need (or want) to deal with the full Linux kernel side implementation.
setup      : |
    # breaks when using the configure macro, so specify supported options manually
    ./configure \
        --prefix=%PREFIX% \
        --libdir=%libdir% \
        --libdevdir=%libdir% \
        --mandir=%PREFIX%/share/man \
        --datadir=%PREFIX%/share
build      : |
    %make
install    : |
    %make_install
