name       : liburing
version    : '2.1'
release    : 2
source     :
    - https://github.com/axboe/liburing/archive/liburing-2.1.tar.gz : f1e0500cb3934b0b61c5020c3999a973c9c93b618faff1eba75aadc95bb03e07
license    : MIT
component  : system.utils
summary    : Library for interacting with the io_uring Linux kernel functionality
description: |
    `liburing` provides helpers to setup and teardown io_uring instances, and also a simplified interface for
    applications that don't need (or want) to deal with the full Linux kernel side implementation.
setup      : |
    # breaks when using the configure macro, so specify supported options manually
    ./configure \
        --prefix=%PREFIX% \
        --libdir=%libdir% \
        --libdevdir=%libdir% \
        --mandir=%PREFIX%/share/man \
        --datadir=%PREFIX%/share
build      : |
    %make
install    : |
    %make_install
