name       : liburing
version    : '2.2'
release    : 3
source     :
    - https://github.com/axboe/liburing/archive/liburing-2.2.tar.gz : e092624af6aa244ade2d52181cc07751ac5caba2f3d63e9240790db9ed130bbc
license    : MIT
component  : system.utils
summary    : Library for interacting with the io_uring Linux kernel functionality
description: |
    `liburing` provides helpers to setup and teardown io_uring instances, and also a simplified interface for applications that don't need (or want) to deal with the full Linux kernel side implementation.
mancompress: yes
setup      : |
    # breaks when using the configure macro, so specify supported options manually
    ./configure \
        --prefix=%PREFIX% \
        --libdir=%libdir% \
        --libdevdir=%libdir% \
        --mandir=%PREFIX%/share/man \
        --datadir=%PREFIX%/share
build      : |
    %make
install    : |
    %make_install
